services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campuswell
      MYSQL_USER: campus
      MYSQL_PASSWORD: campus
    command: --bind-address=0.0.0.0 --port=3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sports-svc/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    networks:
      - campus-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: campuswell
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campus -d campuswell"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - campus-network
    restart: unless-stopped

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: campuswell
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - campus-network
    restart: unless-stopped

  sports-svc:
    build: ./sports-svc
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["8082:8082"]
    networks:
      - campus-network
    restart: unless-stopped

  psych-svc:
    build: ./psych-svc
    environment:
      - SEED_PSYCH=true
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8081:8081"]
    networks:
      - campus-network
    restart: unless-stopped

  habits-svc:
    build: ./habits-svc
    depends_on:
      mongo:
        condition: service_healthy
    ports: ["8083:8083"]
    networks:
      - campus-network
    restart: unless-stopped

  aggregator-svc:
    build: ./aggregator-svc
    depends_on:
      - psych-svc
      - sports-svc
      - habits-svc
    ports: ["8080:8080"]
    networks:
      - campus-network
    restart: unless-stopped

  analytics-svc:
    build: ./analytics-svc
    ports: ["8084:8084"]
    networks:
      - campus-network
    restart: unless-stopped

  frontend:
    profiles: ["ui"]
    build: ./frontend
    ports: ["3000:80"]
    depends_on:
      - aggregator-svc
    environment:
      - REACT_APP_AGGREGATOR_URL=http://aggregator-svc:8080
      - REACT_APP_PSYCH_URL=http://psych-svc:8081
      - REACT_APP_SPORTS_URL=http://sports-svc:8082
      - REACT_APP_HABITS_URL=http://habits-svc:8083
      - REACT_APP_ANALYTICS_URL=http://analytics-svc:8084
    networks:
      - campus-network
    restart: unless-stopped

networks:
  campus-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
  postgres_data: